{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mosaiccore
  version: {{ version|replace("-", "_") }}

source:
  fn: mosaicCore_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mosaicCore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mosaicCore/mosaicCore_{{ version }}.tar.gz
  sha256: 12675850fd03bf1cf14df4e63b080daa5827754bbaeab7429d7c341443376a03

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-dplyr
    - r-lazyeval
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-mass
    - r-dplyr
    - r-lazyeval
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('mosaicCore')"           # [not win]
    - "\"%R%\" -e \"library('mosaicCore')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/mosaicCore
  license: GPL (>= 2)
  summary: Common utilities used in other MOSAIC-family packages are  collected here.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
