{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mosaiccore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mosaicCore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mosaicCore/mosaicCore_{{ version }}.tar.gz
  sha256: dfa1527f8bea0356a8f963b469ddf031039c369032a1665b16c477a2ecef71c0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-dplyr
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-mass
    - r-dplyr
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('mosaicCore')"           # [not win]
    - "\"%R%\" -e \"library('mosaicCore')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/mosaicCore
  license: GPL-2.0-or-later
  summary: Common utilities used in other MOSAIC-family packages are  collected here.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
